### ISSUE TITLE
setTimeout alternative

### ISSUE THREAD

**Issue by gonardfreeman** [salesforce/eslint-plugin-lwc#13]
setTimeout is restricted but there is no alternative, how I can create some styling effects?
for example after click on button I'm adding class to element on page. This class inits some transitions with element and then I want to fire event that will filter out list where this element in. so the element would be deleted before animation would end

**Comment by pmdartus** [comment]
We have observed that, even internally at Salesforce, asynchronous operations are overused and developers use those async operations because they are not aware of component's lifecycle hooks. Because eslint reports an error when using an async operation, developers are required to think twice before using such an API.

While I agree with you that there are plenty of valid use cases (animation, flow control, ...), the eslint rule can always be disabled per line `/* eslint-disable */` if you know that doing an async operation is the right thing to do. If you feel that all the developers on your project have a good understanding of the component lifecycle and how async operations work, you can also disable the rule at the project level in the `.eslintrc`.

The [no-async-operation](https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-async-operation.md) rule is not here to indicate that those APIs are restricted on the Salesforce platform, but rather as a guardrail for developers as the documentation mention.

**Comment by ekashida** [comment]
@gonardfreeman Similar sounding use cases have come up in the past and the `transitionend` event worked out well. Take a look at that before disabling the no-async-operation rule.
